### ISSUE TITLE
Unhandled Exception: HiveError: Box has already been closed.

### ISSUE THREAD

**Issue by Guillergood** [TheCarpetMerchant/hive_multiisolate#2]
Testing your lib I have found some race condition, in which "_getBox" retrieves the box itself, but when you actually try to do some operations with it raises this exception. Forgot to mention that I always retrieve this box in MultiIsolate mode.

Unhandled Exception: HiveError: Box has already been closed.

It is difficult to reproduce as most of the times it seems right,
My suggestion is to try catch this HiveError exception every time "_getBox" is called and try it again in a few milliseconds.
As soon as Github allows me to fork I will code it 😄

**Comment by TheCarpetMerchant** [comment]
I don't see any errors like that in my crashlytics. Most likely it stems from accessing the box very quickly after the previous usage (which I don't think I do in my own use cases), can you see if that could be a probable cause ?

It's weird that this happens to begin with, as the box would have needed to be closed and then the same instance to be reused, which seems like an impossible case here (see BoxBaseImpl.close()). The only possible way seems to be by using the box elsewhere then through a multiisolate box.

So anyway, the best thing to do would be to try and access the box's data (like the `count()`) before returning it in `_getBox` and if the error occurs, try again like it's already doing.

**Comment by Guillergood** [comment]
Sorry for the late response! Yes, the cause of it is accessing the box very quickly (do a "smart" search box checking into the box in multiisolate mode and also doing some tasks in background). The solution that is working for me is to use a non-multiisolate instance for search. Bearing in mind that I will not do any write action with it.

I was thinking something like you are proposing  ``count()`` before returning it in ``_getBox``. This could be a future idea. Thanks for this package, it is very useful. 😄

**Comment by TheCarpetMerchant** [comment]
You can't open a box twice, since the file is locked (see [StorageBackendVm](https://github.com/hivedb/hive/blob/master/hive/lib/src/backend/vm/storage_backend_vm.dart)). That's the whole purpose of this package, working around this problem.
You can also disable locking (using `useLocks`), but that's at your own risk. In this case with one side being read-only, that should work.
