### ISSUE TITLE
Search in the box

### ISSUE THREAD

**Issue by saipranav29** [TheCarpetMerchant/hive_multiisolate#4]
Hey
I am using this package to open and close boxes in main isolate as well as a background isolate to maintain data persistency , Is there any way to perform select query using where condition according to hive syntax using this multiisoalte box. 

This is my query: 

filteredSafeNumber = safeListBox.values
            .where((safeNumberObject) =>
                safeNumberObject.number
                    .toString()
                    .compareTo(number.split("+")[1]) ==
                0)
            .toList();

This is my box : 
safeListBox = HiveMultiIsolateBox<SafeList>(preferences.getString("safe-numbers-box-name")!, isMultiIsolate: true);

This is the error I am facing: 

E/flutter ( 5918): Tried calling: values
E/flutter ( 5918): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter ( 5918): #1      _SplashScreenState.initState.<anonymous closure> (package:scamjam/features/splash_screen/screen/splash_screen.dart:106:42)
E/flutter ( 5918): #2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter ( 5918): #3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 5918): #4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 5918): #5      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
E/flutter ( 5918): #6      _StreamController._add (dart:async/stream_controller.dart:650:7)
E/flutter ( 5918): #7      _StreamController.add (dart:async/stream_controller.dart:598:5)
E/flutter ( 5918): #8      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

**Comment by TheCarpetMerchant** [comment]
The error is right ; there is no getter named `values` on a `HiveMultiIsolateBox`. Use `getAll()`.
