### ISSUE TITLE
Trying to write to multiisolate box using background service 

### ISSUE THREAD

**Issue by saipranav29** [TheCarpetMerchant/hive_multiisolate#5]
I am trying to write to hive multi isolate box when the app is removed from RAM , so I initialized the box in this manner: 

```
  var safeListBox = HiveMultiIsolateBox<SafeList>(
        preferences.getString("safe-numbers-box-name").toString(),
        isMultiIsolate: true);
```

I am getting the error  that hive is not initialized while trying to access this box.
What path must be initialized for the hive constructor?

**Comment by TheCarpetMerchant** [comment]
You need to call `Hive.initFlutter` and the relevant `Hive.registerAdapter` calls before being able to use Hive in a newly spawned Isolate.
In your case you will also need to register the relevant plugin before doing anything else, ie :
```dart
SharedPreferencesAndroid.registerWith();
PathProviderAndroid.registerWith();
await Hive.initFlutter();
// registerAdapter calls
// Opens boxes
```
